### ISSUE TITLE
If Apache cannot write to debug log file, plugin prevents site from loading

### ISSUE THREAD

**Issue by goodpaul** [hxii/YRFW#10]
Versions
PHP v7.2.24
WP v5.3.2
yotpo-reviews-for-woocommerce v2.0.3

Issue
If Apache does not have write access to the plugin, the plugin throws the following error and the site doesn't load even if debugging is not enabled:
`Can't open ./wp-content/plugins/yotpo-reviews-for-woocommerce/yotpo_debug.log!`

**Comment by hxii** [comment]
Resolved by #12
