### ISSUE TITLE
Serve resources from a consistent URL

### ISSUE THREAD

**Issue by robwatson-intechra** [hxii/YRFW#13]
I'm constantly taking a performance hit on Intechrahealth.com because of the Yotpo software not serving its resources from a consistent URL. Is there any way that this issue can be fixed?

[https://gtmetrix.com/reports/intechrahealth.com/QOSz21et](https://gtmetrix.com/reports/intechrahealth.com/QOSz21et)

Thanks.

**Comment by hxii** [comment]
Hey @robwatson-intechra the impact you're seeing is due to Yotpo's tracking pixel and is not actually visible or felt by an end user.
You can try and contact Yotpo support about it, as it's not related to the plugin.
