### ISSUE TITLE
Serve resources from a consistent URL - official plugin and this one calling same information?

### ISSUE THREAD

**Issue by ALinedDesign** [hxii/YRFW#6]
Howdy

I think this plugin and Yotpo reviews are both calling the same information slightly differently and it's having a large impact of pagespeed scores.

I.e. my client site:
https://staticw2.yotpo.com/bJm5Kw04krT4uzcE8cv6XETzSWRY3HauojOqc6Hd/widget.css?widget_version=

https://staticw2.yotpo.com/bJm5Kw04krT4uzcE8cv6XETzSWRY3HauojOqc6Hd/widget.css?widget_version=2019-12-26_08-05-16

Any way to consolidate?

**Comment by hxii** [comment]
Hey, @ALinedDesign can you show me an example?
The way it works is that YRFW gets the version, stores it in the cache for an hour and then calls the CSS and font via `preload` using the version.
This is the code in question: https://github.com/hxii/YRFW/blob/master/inc/Base/class-yrfw-assets.php#L90

What you are describing could mean that the version is not stored.

**Comment by ALinedDesign** [comment]
Sure!

https://gtmetrix.com/reports/www.cherishskincare.com.au/dRh1z5vy

Trying to nut out what's going on re consistent url warning.

**Comment by hxii** [comment]
So it looks like my assumption was correct - the version string is not being saved.
Would you be able to take a quick look at the logs and let me know if you see any errors?

As a quick fix, you could comment out these two lines:
https://github.com/hxii/YRFW/blob/master/inc/Base/class-yrfw-assets.php#L69-L70

**Comment by ALinedDesign** [comment]
I'm so sorry - I'm a bit of a noob. Where will I find the error logs?
Sarah Crawford
Website Consultant
hello@alineddesign.com
A Lined Design | https://www.alineddesign.com

<https://www.facebook.com/alineddesigncreative/>
<https://www.linkedin.com/in/sarah-crawford-website-consultant/>
<https://www.pinterest.com.au/alineddesign/> *Working hard on these days*
0900 - 1430 Mon
0900 - 1700 Wed - Fri



*I do not work Tuesdays. To keep my workflow efficient I check my emails
twice each day.*


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by hxii** [comment]
It depends. If you have debugging mode enabled in WordPress, you'll probably be able to see any errors in the debug file defined (by default it's `wp-content/debug.log`).

Alternatively, you'll most likely be able to see any errors in your PHP Error Log.

If you'd rather just quickly fix the issue - commenting out the aforementioned lines should help.

**Comment by ALinedDesign** [comment]
That worked perfectly - thanks.
Sarah Crawford
Website Consultant
hello@alineddesign.com
A Lined Design | https://www.alineddesign.com

<https://www.facebook.com/alineddesigncreative/>
<https://www.linkedin.com/in/sarah-crawford-website-consultant/>
<https://www.pinterest.com.au/alineddesign/> *Working hard on these days*
0900 - 1430 Mon
0900 - 1700 Wed - Fri



*I do not work Tuesdays. To keep my workflow efficient I check my emails
twice each day.*


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*
